version: '3.9'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    depends_on: []
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - VITE_API_BASE_URL=http://localhost:5000
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped


